// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// sibosp_reset //
// ------------ //

#define sibosp_reset_wrap_target 31
#define sibosp_reset_wrap 31

static const uint16_t sibosp_reset_program_instructions[] = {
    0xe02b, //  0: set    x, 11                      
    0xf301, //  1: set    pins, 1                [19]
    0xb342, //  2: nop                           [19]
    0xb342, //  3: nop                           [19]
    0xb342, //  4: nop                           [19]
    0xb342, //  5: nop                           [19]
    0xb342, //  6: nop                           [19]
    0xb342, //  7: nop                           [19]
    0xb342, //  8: nop                           [19]
    0xb342, //  9: nop                           [19]
    0xb342, // 10: nop                           [19]
    0xb342, // 11: nop                           [19]
    0xb342, // 12: nop                           [19]
    0xf300, // 13: set    pins, 0                [19]
    0xb342, // 14: nop                           [19]
    0xb342, // 15: nop                           [19]
    0xb342, // 16: nop                           [19]
    0xb342, // 17: nop                           [19]
    0xb342, // 18: nop                           [19]
    0xb342, // 19: nop                           [19]
    0xb342, // 20: nop                           [19]
    0xb342, // 21: nop                           [19]
    0xb342, // 22: nop                           [19]
    0xb342, // 23: nop                           [19]
    0xb342, // 24: nop                           [19]
    0xb342, // 25: nop                           [19]
    0xb342, // 26: nop                           [19]
    0xb342, // 27: nop                           [19]
    0xb342, // 28: nop                           [19]
    0xb342, // 29: nop                           [19]
    0x1341, // 30: jmp    x--, 1                 [19]
            //     .wrap_target
    0xa042, // 31: nop                               
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sibosp_reset_program = {
    .instructions = sibosp_reset_program_instructions,
    .length = 32,
    .origin = -1,
};

static inline pio_sm_config sibosp_reset_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sibosp_reset_wrap_target, offset + sibosp_reset_wrap);
    return c;
}

void sibosp_reset_program_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    pio_sm_config c = sibosp_reset_program_get_default_config(offset);
    pio_gpio_init(pio, pin);
    sm_config_set_set_pins (&c, pin, 1);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

